spring.application.name=money-transfer-system

#Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mts}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Abhi_2005}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

logging.level.org.springframework.security=INFO
logging.level.com.bd=INFO

# JWT settings
security.jwt.secret=change-me-please-replace-with-long-random-secret
security.jwt.expiration-ms=3600000
